import "../Styles/akstyle.scss";
import "./Vendor/jquery-ui.js";
import "./Vendor/jquery.multi-select.js";
import "./general.js";
import "./vueapps.js";
import "./profile.js";
import "./upcoming.js";
import "./musicplayer.js";
import "./calendar.js";
import "./Vendor/chosen.jquery.min.js";

import "./Admin/menuedit.js";
import "./Admin/pageedit.js";
import "./Admin/users.js";
import "./Admin/newusers.js";
import "./Admin/media.js";
import "./Admin/events.js";
import "./Admin/recruits.js";
import "./Admin/album.js";