import { Translation } from "./models";

export const musicTranslations: Record<string, Translation> = {
  "show-albums": { swedish: "Visa album", english: "Show albums" },
  "search-songs": { swedish: "Sök låtar", english: "Search songs" },
  "search-here": { swedish: "Sök här", english: "Search here" },
  "album-from-gpt": {
    swedish: "Albumbeskrivning genererad av ChatGPT",
    english: "Album description generated by ChatGPT"
  }
};
